services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile # C'est le Dockerfile du Backend
    image: square-backend
    container_name: square_backend
    ports:
      - "8000:8000"
    # Sets backend as api domain
    hostname: backend 
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile # Le Dockerfile que nous venons de créer
    image: square-frontend
    container_name: square_frontend
    ports:
      - "8501:8501" # Port par défaut de Streamlit
    environment:
      # Optionnel, mais bonne pratique, bien que le nom de service suffise
      API_BASE_URL: http://backend:8000 
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge