services:
  backend:
    build:
      context: .
      dockerfile: src/cicd/backend/Dockerfile
    image: square-backend
    container_name: square_backend
    ports:
      - "8000:8000"
    # Sets backend as api domain
    hostname: backend 
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: src/cicd/frontend/Dockerfile
    image: square-frontend
    container_name: square_frontend
    ports:
      - "8501:8501"
    environment:
      # Optionnel, mais bonne pratique, bien que le nom de service suffise
      API_BASE_URL: http://backend:8000 
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge