name: Docker publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Tags semver uniquement

jobs:
  docker-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: â¬‡ï¸ Checkout du code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: ğŸ·ï¸ Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/square-backend
          ${{ secrets.DOCKERHUB_USERNAME }}/square-frontend
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: ğŸ³ Dockerhub logging
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: ğŸ”¨ Build and Push Backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/cicd/backend/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: ğŸ”¨ Build and Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/cicd/frontend/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}